f=open("File.txt", "r")
# f=open("File.txt", "a")
# print(f.read())
# print(f.fileno())
# f.write("\nThis New Line added Through")
# f.flush()
# print(f.isatty())
# f.write("-By Rajat Bais")
print(f.read())
f.close()
